"""add student and industrialist interest tables

Revision ID: b54f35353630
Revises: rewards20260922
Create Date: 2026-09-22 22:42:25.963750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54f35353630'
down_revision: Union[str, Sequence[str], None] = 'rewards20260922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industrialist_interests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=False),
    sa.Column('designation', sa.Text(), nullable=True),
    sa.Column('industry_domain', sa.Text(), nullable=True),
    sa.Column('focus_areas', sa.Text(), nullable=True),
    sa.Column('company_website', sa.Text(), nullable=True),
    sa.Column('sponsorship_capacity', sa.Text(), nullable=True),
    sa.Column('collaboration_goals', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', name='uq_industrialist_interests_profile_id')
    )
    op.create_index(op.f('ix_industrialist_interests_profile_id'), 'industrialist_interests', ['profile_id'], unique=False)
    op.create_table('student_interests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('institution_name', sa.Text(), nullable=False),
    sa.Column('degree_program', sa.Text(), nullable=True),
    sa.Column('field_of_study', sa.Text(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('interest_areas', sa.Text(), nullable=True),
    sa.Column('portfolio_url', sa.Text(), nullable=True),
    sa.Column('github_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', name='uq_student_interests_profile_id')
    )
    op.create_index(op.f('ix_student_interests_profile_id'), 'student_interests', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_interests_profile_id'), table_name='student_interests')
    op.drop_table('student_interests')
    op.drop_index(op.f('ix_industrialist_interests_profile_id'), table_name='industrialist_interests')
    op.drop_table('industrialist_interests')
    # ### end Alembic commands ###
