"""add avatar_url location and updated_at to profiles

Revision ID: ba3667551077
Revises: d2fd2379493d
Create Date: 2026-09-12 12:14:59.491959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba3667551077'
down_revision: Union[str, Sequence[str], None] = 'd2fd2379493d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('avatar_url', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('location', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'updated_at')
    op.drop_column('profiles', 'location')
    op.drop_column('profiles', 'avatar_url')
    # ### end Alembic commands ###
