"""add phone_number to profiles

Revision ID: d2fd2379493d
Revises: ca4f00f757e1
Create Date: 2026-09-12 12:09:57.523418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2fd2379493d'
down_revision: Union[str, Sequence[str], None] = 'ca4f00f757e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('phone_number', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'phone_number')
    # ### end Alembic commands ###
