"""create notifications table

Revision ID: d95b2447d881
Revises: 25573d3958f1
Create Date: 2026-09-22 23:56:26.530263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95b2447d881'
down_revision: Union[str, Sequence[str], None] = '25573d3958f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_issue_id', sa.UUID(), nullable=True),
    sa.Column('related_application_id', sa.UUID(), nullable=True),
    sa.Column('related_collaboration_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_collaboration_id'], ['collaborations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_issue_id'], ['issues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_application_id'), 'notifications', ['related_application_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_collaboration_id'), 'notifications', ['related_collaboration_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_issue_id'), 'notifications', ['related_issue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_related_issue_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_collaboration_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_application_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
